name: Main

on: [push]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MINIO_REGION: us-west-1
      MINIO_SSL: false
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: password
      MINIO_ENDPOINT: localhost
      PG_CONNECTION_STRING: postgres://postgres:password@localhost:5432
      PG_DB: postgres

    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '14'
          postgresql user: postgres
          postgresql password: password

      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio -e "MINIO_ROOT_USER=root" -e "MINIO_ROOT_PASSWORD=password" -v /tmp/data:/data -v /tmp/config:/root/.minio minio/minio server /data

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check types
        run: yarn type-check

      - name: Check linting
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

      - name: Build storybook
        run: yarn build-storybook

      - name: Build package
        run: yarn build

      - name: Setup examples
        run: |
          cd examples/next-upload-example
          yarn install --frozen-lockfile
          yarn link next-upload
          yarn build

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5
